name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    name: Node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: check circular dependencies
        run: npm run madge:circular
      - name: test
        run: npm test
  publish:
    name: Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm ci
        run: npm ci
      - name: build typescript
        run: npm run build
      - name: generate build number
          uses: einaregilsson/build-number@v2
          with:
            token: ${{ secrets.github_token }}
      - name: set version
        run: npm --no-git-tag-version version "0.1.$BUILD_NUMBER"
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}